<?php if($this->isRenderBottomlineQna()){ ?>
<style>
    .yotpo-icon-double-bubble, .yotpo-stars { margin: 0 5px 0 0 !important; }
    div.yotpo.bottomLine { display: inline-block; margin: 0 10px 1px 0;}
    .thumbnail .yotpo a { display: inline-block; }
    div.yotpo.QABottomLine { display: inline-block; }
</style>
<?php } ?>

<?php if( $this->isRenderBottomline()) { ?>
<div class="yotpo bottomLine"
	data-product-id="<?php echo $this->getProductId() ?>"
	data-url="<?php echo $this->getProductUrl() ?>">
</div>
<?php } ?>

<?php	if($this->isRenderBottomlineQna()){ ?>
        <div class="yotpo QABottomLine"
			data-appkey="<?php echo $this->getAppKey() ?>"
			data-product-id="<?php echo $this->getProductId() ?>">
		</div>
<?php } ?>