<?php if( $this->isRenderBottomline()) { ?>
<div class="yotpo bottomLine bottomline-position"
	data-product-id="<?php echo $this->getProductId() ?>"
	data-url="<?php echo $this->getProductUrl() ?>">
</div>
<?php } ?>

<?php	if($this->isRenderBottomlineQna()){ ?>
        <div class="yotpo QABottomLine"
			data-appkey="<?php echo $this->getAppKey() ?>"
			data-product-id="<?php echo $this->getProductId() ?>">
		</div>
<?php } ?>