<?php
/**
 * @var $block \Yotpo\Yotpo\Block\Yotpo
 */
?>
<?php if (!($block->isEnabled() && ($block->isRenderBottomline() || $block->isRenderBottomlineQna()))) {
    return;
} ?>
<!-- Yotpo - BottomLine -->
<div class="yotpoBottomLine">
	<?php if ($block->isRenderBottomline()): ?>
		<div class="yotpo bottomLine bottomline-position"
			data-product-id="<?php echo $block->getProductId() ?>"
			data-url="<?php echo $block->getProductUrl() ?>">
		</div>
	<?php endif; ?>
	<?php if ($this->isRenderBottomlineQna()): ?>
        <div class="yotpo QABottomLine"
			data-appkey="<?php echo $block->getAppKey() ?>"
			data-product-id="<?php echo $block->getProductId() ?>">
		</div>
	<?php endif; ?>
</div>
<!--/ Yotpo - BottomLine -->
