<?php
/**
 * @var $block \Yotpo\Yotpo\Block\Yotpo
 */
?>
<?php if (!$block->isEnabled()) {
    return;
}
?>
<!-- Yotpo - Widget Script -->
<script type="text/javascript">
    (function e(){var e=document.createElement("script");e.type="text/javascript",e.async=true,e.src="<?= $block->getYotpoWidgetUrl() ?>";var t=document.getElementsByTagName("script")[0];t.parentNode.insertBefore(e,t)})();
</script>
<!--/ Yotpo - Widget Script -->
