<?php
/**
 * @var $block \Yotpo\Yotpo\Block\Yotpo
 */
?>
<?php if (!($block->isEnabled() && $block->isRenderWidget() && $block->hasProduct())) {
    return;
}
?>
<!-- Yotpo - Widget Div -->
<?php if ($block->isRenderWidget()): ?>
	<div class="yotpo yotpo-main-widget"
		 data-product-id="<?php echo $block->getProductId(); ?>"
		 data-name="<?php echo $block->getProductName(); ?>"
		 data-description="<?php echo $block->getProductDescription(); ?>"
		 data-url="<?php echo $block->getProductUrl(); ?>"
		 data-image-url="<?php echo $block->getProductImageUrl(); ?>"
         data-price="<?php echo $block->getProductFinalPrice(); ?>"
         data-currency="<?php echo $block->getCurrentCurrencyCode(); ?>">
     </div>
<?php endif; ?>
<!--/ Yotpo - Widget Div -->
