<?php
?>

<script type="text/javascript">
    //<![CDATA[
    function exportOrders() {debugger;
    var params = {
                form_key : FORM_KEY,
                store_id : '<?php echo $this->getStoreId() ?>'
            };
    var url = '<?php echo $this->getAjaxExportUrl() ?>';
    new Ajax.Request(url , {
                parameters:params,
                method:'post',
                onComplete:function(transport) {
                   location.reload();
                }
        });
    }
    //]]>
</script>

<?php echo $this->getButtonHtml(); ?>
<p style="color: #303030;
    font-size: 12px;
    margin: 5px 0;">Please be patient, this may take a while. </p>