<?php
/**
 * @var $block \Yotpo\Yotpo\Block\Adminhtml\System\Config\LaunchYotpoButton
 */
?>
<?php if (!$block->isStoreScope()) : ?>
    <p class="note"><?= __('Yotpo can only be connected, enabled, or disabled via the Store View menu.<br>To connect your App Key and API secret, first select the relevant Store View.') ?></p>
    <p></p>
<?php endif; ?>
<p class="note">
    <?= __('Need help?') ?> <a href="https://docs.magento.com/m2/ee/user_guide/marketing/yotpo-connect.html" target="_blank" title="<?= __('Setup Guide') ?>"><?= __('Setup Guide') ?></a>
</p>
