<?php
/**
 * @var $block \Yotpo\Yotpo\Block\Adminhtml\System\Config\Form\Field\SyncStatus
 */
$status = $block->getStatus();
?>
<!-- Yotpo Sync Status -->
<div><?= __('Sync progress: %1', $status['total_orders_synced'] . '/' . $status['total_orders']) ?></div>
<div><?= __('Last sync date: %1', $status['last_sync_date']) ?></div>
<div><?= __('Total orders synced with Yotpo: %1', $status['total_orders_synced_all']) ?></div>
<!--/ Yotpo Sync Status -->
