<?php
/**
 * @var $block \Yotpo\Yotpo\Block\Adminhtml\System\Config\Form\YotpoButton
 */
?>
<!-- Yotpo Button (Generate reviews for my past orders) -->
<script type="text/javascript">
    //<![CDATA[
    function exportOrders() {//debugger;
        new Ajax.Request('<?php echo $this->getAjaxExportUrl() ?>' , {
            parameters: {
                form_key : FORM_KEY,
                store_id : '<?php echo $this->getStoreId() ?>'
            },
            method:'post',
            onComplete:function(transport) {
                location.reload();
            },
            onFailure: function(transport){
                console.log(transport.responseText);
                alert("An error occured while trying to export past orders!");
                location.reload();
            }
        });
    }
    //]]>
</script>

<?php echo $this->getButtonHtml(); ?>
<p style="color:#303030;font-size:12px;margin: 5px 0;">Please be patient, this may take a while.</p>
<!--/ Yotpo Button (Generate reviews for my past orders) -->
