<?php
/**
 * @var $block \Yotpo\Yotpo\Block\Adminhtml\System\Config\Form\YotpoButton
 */
?>
<!-- Yotpo Button (Generate reviews for my past orders) -->
<script type="text/javascript">
    //<![CDATA[
    (function  () {
        require([
            "jquery"
        ],function($) {
            window.yotpoExportOrders = function(){//debugger;
                $.ajax({
                    url: '<?php echo $block->getAjaxExportUrl() ?>',
                    type: 'POST',
                    data: {
                        form_key : FORM_KEY,
                        stores: <?php echo json_encode($block->getStoreIds(), true); ?>
                    },
                    showLoader: true
                }).done(function (response) {
                    console.log(response);
                    location.reload();
                }).fail(function (response) {
                    console.log(response);
                    alert("An error occured while trying to export past orders!");
                    location.reload();
                });
            };
            document.getElementById("yotpo-export-button").style.display = "block";
        });
    })();
    //]]>
</script>

<?php echo $block->getButtonHtml(); ?>
<p class="note">
    Reviews from past orders are collected by the current configuration scope:<br>
    <b>Default:</b> Applies to all stores<br>
    <b>Website:</b> Applies only to child stores<br>
    <b>Store:</b> Applies only to the current store<br>
    <p style="font-style:italic;">Please be patient, this may take a while.</p>
</p>
<!--/ Yotpo Button (Generate reviews for my past orders) -->
