<?php
/**
 * @var $block Yotpo\Yotpo\Block\Adminhtml\Dashboard\Tab\YotpoReviews
 */
?>
<?php if ($block->isAppKeyAndSecretSet()): ?>
    <div class="yotpo-reviews-totals" id="yotpo_reviews_totals">
        <?php if (sizeof($block->getTotals()) > 0): ?>
            <ul class="yotpo-reviews-totals-list">
                <?php foreach ($block->getTotals() as $_total): ?>
                    <li class="yotpo-reviews-totals-item <?php echo /* @escapeNotVerified */ $_total['class']; ?>">
                        <span class="yotpo-reviews-totals-label"><?php echo /* @escapeNotVerified */ $_total['label']; ?></span>
                        <strong class="yotpo-reviews-totals-value"><?php echo /* @escapeNotVerified */ $_total['value']; ?></strong>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <div class="yotpo-reviews-totals-nodata">
                <?php echo __("No Data Found"); ?>
            </div>
        <?php endif; ?>
    </div>
    <div><?php echo $block->getLounchYotpoButtonHtml(); ?></div>
<?php else: ?>
    <div class="yotpo-reviews-totals-no-appkey">
        <div class="collect-and-leverage">
            <?php echo __("Collect and leverage customer reviews, ratings, and Q&A<br>with Yotpo's AI-powered tools and on-site widgets."); ?>
        </div>
        <div><?php echo $block->getLounchYotpoButtonHtml(); ?></div>
        <div class="already-have-account">
            <?php echo __("Already have an account?"); ?> <a href="<?php echo $block->getYotpoConfigUrl(); ?>" title="<?php echo __("Connect Yotpo"); ?>"><?php echo __("Connect Yotpo"); ?></a>
        </div>
    </div>
<?php endif; ?>
